# Generated by Django 2.2.1 on 2020-06-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0003_auto_20200614_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
