# Generated by Django 2.2.1 on 2020-06-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0004_show_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
