# Generated by Django 2.2.1 on 2020-06-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0005_show_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255, null=True)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '留言板',
                'verbose_name_plural': '留言板',
                'db_table': 'Note',
            },
        ),
    ]
