# Generated by Django 2.2.1 on 2020-06-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0006_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='data',
            field=models.CharField(max_length=6000, null=True),
        ),
    ]
