# Generated by Django 2.2.1 on 2020-06-18 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0007_auto_20200616_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
    ]
