# Generated by Django 2.2.1 on 2020-06-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.CharField(max_length=32)),
                ('time0', models.CharField(max_length=32)),
                ('remark', models.CharField(max_length=32)),
                ('current', models.CharField(max_length=32)),
                ('sent', models.CharField(max_length=32)),
                ('file', models.CharField(max_length=32)),
                ('time1', models.CharField(max_length=32)),
                ('end', models.CharField(max_length=32)),
                ('duty_time', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '现行补贴发放标准',
                'verbose_name_plural': '现行补贴发放标准',
                'db_table': 'Current_sub',
            },
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.CharField(max_length=32)),
                ('time0', models.CharField(max_length=32)),
                ('remark', models.CharField(max_length=32)),
                ('current', models.CharField(max_length=32)),
                ('wage_level', models.CharField(max_length=32)),
                ('seq', models.CharField(max_length=32)),
                ('duty', models.CharField(max_length=32)),
                ('duty_seq', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '职务工资发放标准表',
                'verbose_name_plural': '职务工资发放标准表',
                'db_table': 'Salary_Duty',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.CharField(max_length=32)),
                ('time0', models.CharField(max_length=32)),
                ('remark', models.CharField(max_length=32)),
                ('current', models.CharField(max_length=32)),
                ('wage_level', models.CharField(max_length=32)),
                ('seq', models.CharField(max_length=32)),
                ('grade', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '级别工资发放标准表',
                'verbose_name_plural': '级别工资发放标准表',
                'db_table': 'Salary_Level',
            },
        ),
        migrations.CreateModel(
            name='Police_rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.CharField(max_length=32)),
                ('time0', models.CharField(max_length=32)),
                ('remark', models.CharField(max_length=32)),
                ('current', models.CharField(max_length=32)),
                ('sent', models.CharField(max_length=32)),
                ('seq', models.CharField(max_length=32)),
                ('police', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '警衔工资发放标准表',
                'verbose_name_plural': '警衔工资发放标准表',
                'db_table': 'Police_rank',
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.CharField(max_length=32)),
                ('time0', models.CharField(max_length=32)),
                ('remark', models.CharField(max_length=32)),
                ('current', models.CharField(max_length=32)),
                ('sent', models.CharField(max_length=32)),
                ('file', models.CharField(max_length=32)),
                ('time1', models.CharField(max_length=32)),
                ('end', models.CharField(max_length=32)),
                ('level', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '公务交通补贴发放标准',
                'verbose_name_plural': '公务交通补贴发放标准',
                'db_table': 'Traffic',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.IntegerField()),
                ('name', models.CharField(max_length=32, null=True)),
                ('wage_card', models.CharField(max_length=32)),
                ('seq', models.CharField(max_length=32)),
                ('open', models.CharField(max_length=32)),
                ('idcard', models.CharField(max_length=18, null=True)),
                ('status', models.CharField(max_length=32)),
                ('remark', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=32)),
                ('service', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '工资卡号信息集',
                'verbose_name_plural': '工资卡号信息集',
                'db_table': 'User_detail',
            },
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=64)),
                ('change', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('mine', models.ForeignKey(on_delete=True, to='user.User')),
            ],
            options={
                'verbose_name': '工资发放信息说明表',
                'verbose_name_plural': '工资发放信息说明表',
                'db_table': 'Salary_change',
            },
        ),
        migrations.CreateModel(
            name='Salary_sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=32, null=True)),
                ('level', models.CharField(max_length=32, null=True)),
                ('station', models.CharField(max_length=32, null=True)),
                ('salary_post', models.CharField(max_length=32, null=True)),
                ('tcgrade', models.CharField(max_length=32, null=True)),
                ('teacher', models.CharField(max_length=32, null=True)),
                ('police_rank', models.CharField(max_length=32, null=True)),
                ('industry', models.CharField(max_length=32, null=True)),
                ('maim', models.CharField(max_length=32, null=True)),
                ('allowance', models.CharField(max_length=32, null=True)),
                ('special', models.CharField(max_length=32, null=True)),
                ('heart', models.CharField(max_length=32, null=True)),
                ('only_child', models.CharField(max_length=32, null=True)),
                ('phone_fee', models.CharField(max_length=32, null=True)),
                ('current_subsiby', models.CharField(max_length=32, null=True)),
                ('traffic', models.CharField(max_length=32, null=True)),
                ('others', models.CharField(max_length=32, null=True)),
                ('thurber', models.CharField(max_length=32, null=True)),
                ('reissue', models.CharField(max_length=32, null=True)),
                ('other2', models.CharField(max_length=32, null=True)),
                ('individual', models.CharField(max_length=32, null=True)),
                ('fiscal', models.CharField(max_length=32, null=True)),
                ('profession', models.CharField(max_length=32, null=True)),
                ('should', models.CharField(max_length=32, null=True)),
                ('income', models.CharField(max_length=32, null=True)),
                ('house', models.CharField(max_length=32, null=True)),
                ('lose', models.CharField(max_length=32, null=True)),
                ('hospital', models.CharField(max_length=32, null=True)),
                ('combined', models.CharField(max_length=32, null=True)),
                ('other_item', models.CharField(max_length=32, null=True)),
                ('other_item1', models.CharField(max_length=32, null=True)),
                ('salary_pay', models.CharField(max_length=32, null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('msg', models.ForeignKey(on_delete=True, to='user.User')),
            ],
            options={
                'verbose_name': '市政统发工资表',
                'verbose_name_plural': '市政统发工资表',
                'db_table': 'Salary_sheet',
            },
        ),
    ]
