# Generated by Django 2.2.1 on 2020-06-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_sheet',
            name='msg',
        ),
        migrations.AddField(
            model_name='user',
            name='msg',
            field=models.ForeignKey(null=True, on_delete=True, to='user.Salary_sheet'),
        ),
    ]
