# Generated by Django 2.2.1 on 2020-06-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200609_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
