# Generated by Django 2.2.1 on 2020-06-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(default='888888', max_length=32, null=True),
        ),
    ]
