# Generated by Django 2.2.1 on 2020-06-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200610_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='msg',
        ),
        migrations.AddField(
            model_name='salary_sheet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=True, to='user.User'),
        ),
    ]
