# Generated by Django 2.2.1 on 2020-06-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200617_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '下发文件的评论表', 'verbose_name_plural': '下发文件的评论表'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
    ]
