# Generated by Django 2.2.1 on 2020-06-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200617_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, null=True)),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('create_time', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': '上级下发文件内容',
                'verbose_name_plural': '上级下发文件内容',
                'db_table': 'Show',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=True, to='user.Show'),
        ),
    ]
