# Generated by Django 2.2.1 on 2020-06-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200618_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.IntegerField(null=True),
        ),
    ]
