# Generated by Django 2.2.1 on 2020-06-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200619_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.IntegerField(default='1', null=True),
        ),
    ]
