# Generated by Django 2.2.1 on 2020-06-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_show_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='cover',
        ),
        migrations.AddField(
            model_name='show',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
