# Generated by Django 2.2.1 on 2020-06-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200627_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duty',
            name='views',
        ),
    ]
