# Generated by Django 2.2.1 on 2020-06-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_duty_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_sub',
            name='accord',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='current_sub',
            name='start',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='duty',
            name='accord',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='duty',
            name='end',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='duty',
            name='start',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='accord',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='end',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='start',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='police_rank',
            name='accord',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='police_rank',
            name='end',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='police_rank',
            name='start',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='traffic',
            name='accord',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='traffic',
            name='start',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
