# Generated by Django 2.2.1 on 2020-06-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200629_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_sub',
            name='duty_time',
        ),
        migrations.RemoveField(
            model_name='current_sub',
            name='file',
        ),
        migrations.RemoveField(
            model_name='current_sub',
            name='time1',
        ),
        migrations.AddField(
            model_name='current_sub',
            name='duty',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='current_sub',
            name='end',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
