# Generated by Django 2.2.1 on 2020-07-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200629_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '留言板上的说说', 'verbose_name_plural': '留言板上的说说'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tim', models.DateTimeField(auto_now_add=True)),
                ('data', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=32, null=True)),
                ('user', models.ForeignKey(on_delete=True, to='user.User')),
            ],
            options={
                'verbose_name': '回复的信息',
                'verbose_name_plural': '回复的信息',
                'db_table': 'reply',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=True, to='user.reply'),
        ),
    ]
